### ISSUE TITLE
Not an issue, but dont know how else to comment

### ISSUE THREAD

**Issue by Cheetokps** [hammerandchisel/airhornbot#13]
There should be a !snoop or !weed or !snoopdogg command that plays the smoke weed everyday audio, as well as a !pacer or !pacertest command that plays pacer test audio. Also, a !rickastley or !rickroll command that plays Rick Astley's Never Gonna Give You Up

**Comment by SaiZa** [comment]
Would love to have the John Cena trumpets added as well :P

**Comment by LucaVazz** [comment]
I think this falls into the same realm as #21:
> we're not looking to add more sounds to the official airhorn bot right now, but feel free to make your own and use whatever sounds you like!
