### ISSUE TITLE
running gcc failed: fork/exec /usr/bin/gcc: cannot allocate memory

### ISSUE THREAD

**Issue by diegogarciamendoza** [hammerandchisel/airhornbot#7]
I'm trying to run it in a digital ocean droplet using Ubuntu 15.10 and when I'm getting the bot with the command 
`go get github.com/hammerandchisel/airhornbot/cmd/bot`

Appears this message
`running gcc failed: fork/exec /usr/bin/gcc: cannot allocate memory`

Any idea why is this happening? I'm new on Go but very interested on learning more about it and your project seems like an excelent example.

**Comment by jhgg** [comment]
Hi. This means you ran out of memory trying to compile. :( I would
recommend using a bigger droplet to compile. Then down sizing
https://www.digitalocean.com/community/tutorials/how-to-downgrade-digitalocean-droplets
